name: flutter_application_7
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '^3.7.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
   assets:
    - assets/images/araikusik.jpg
    - assets/images/kkkkkkk.JPG
    - assets/images/clothes.JPG
    - assets/images/hoodie.jpg
    - assets/images/show.JPG
    - assets/images/pen.JPG
    - assets/images/cap.jpg
    - assets/images/book.JPG
    - assets/images/bag.jpg
    - assets/images/clothes4.JPG
    - assets/images/IMG_1620.JPG
    - assets/images/IMG_1877.JPG
    - assets/images/IMG_1893.JPG
    - assets/images/IMG_1784.JPG
    - assets/images/IMAGE 2025-05-29 12:09:57.jpg
    - assets/images/IMAGE 2025-05-29 12:11:00.jpg
    - assets/images/IMAGE 2025-05-29 12:13:02.jpg
    - assets/images/IMG_1749.JPG
    - assets/images/IMG_1746.JPG